### ISSUE TITLE
GPU not detected

### ISSUE THREAD

**Issue by himaniyadav** [quinngroup/parkinsons_multimodal#1]
When I run `main.py` on the master branch, only the CPU is detected. The first line of output is:
`[INFO] Device detected: cpu`
This is despite nvidia-smi output showing that the GPU is properly working on logan. I've also tried to restart logan and the same issue occurs.
The gpu has been detected before, after a restart of logan, but it has since stopped working, so I'm not sure whether it's an issue with the code or with logan. The code I'm using has all been pushed onto the main branch.

![image](https://user-images.githubusercontent.com/30757425/136878774-b23205cd-6628-410d-af91-0e173da93d26.png)

**Comment by Micky774** [comment]
What code actually outputs the `[INFO] Device detected: cpu` statement? Like specifically what line in `main.py` is the source of this message?

**Comment by himaniyadav** [comment]
It's line 107 of src/Models/VAE.py, when initializing the VAE.

**Comment by Micky774** [comment]
Okay, so testing it from your user environment, it looks like `torch.cuda.is_available()` returns `False` globally -- not just in this example python program. This indicates that you have the wrong version of pytorch installed. You should have, when installing it via their website, used this setup/command: 
![image](https://user-images.githubusercontent.com/34613774/136881563-ec5ca3af-7dee-4294-9124-f3ade0abc1b3.png)

On that note, I would suggest you use anaconda to manage these kinds of environments (if you don't already).

Reinstall then try it out again

Edit: Here's the actual command if you want to copy-and-paste: `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia`

**Comment by magsol** [comment]
Happy to help with the anaconda setup if needed; that's definitely the way to go for managing a consistent Python environment.

**Comment by himaniyadav** [comment]
I think that worked, thank you!
